### getAlbumesAll
GET http://localhost:3000/api/v1/albumes

### getAlbumesAll
GET http://localhost:3000/api/v1/albumes?nombre=Abbey

### getAlbumesAll
GET http://localhost:3000/api/v1/albumes?nombre=Abbey&artista=Beatles

### getAlbumesAll
GET http://localhost:3000/api/v1/albumes?artista=Beatles

### gatAlbumById
GET http://localhost:3000/api/v1/albumes/1

### gatAlbumById (uno que no existe)
GET http://localhost:3000/api/v1/albumes/3

### Nuevo álbum
POST http://localhost:3000/api/v1/albumes
Content-Type: application/json

{
  "nombre": "Un Verano Sin Ti",
  "artista": "Bad Bunny",
  "genero": "Reggaeton",
  "precio": 25.99
}

### Actualiza álbum
PUT http://localhost:3000/api/v1/albumes/1
Content-Type: application/json

{
  "nombre": "Abbey Road (Remastered)",
  "artista": "The Beatles",
  "genero": "Rock",
  "precio": 22.99
}


### Delete álbum
DELETE http://localhost:3000/api/v1/albumes/2